name: Python application test with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main 
        
      - name: Set working directory
        run: |
          cd $GITHUB_WORKSPACE

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
       

      - name: Debug Info
        run: |
          echo "Current directory: $(pwd)"
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          echo "Contents of workspace: $(ls -la $GITHUB_WORKSPACE)"

      - name: Create virtual environment
        run: python3 -m venv venv

      - name: Activate virtual environment
        run: source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: List Files in Directory
        run: |
          ls -la
      - name: Lint with pylint
        run: make lint

      - name: Run unit tests
        run: make test

      - name: Run Makefile
        run: |
          make format